apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: world
  name: world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world
  template:
    metadata:
      labels:
        app: world
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "world-service"
        dapr.io/app-port: "8089"
    spec:
      containers:
        - image: ghcr.io/pauldotyu/dapr-demos/world-service:latest
          name: world-container
          resources: {}
          ports:
            - containerPort: 8089
