name: Build Docker Images

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_TOKEN }}
      - name: Get the tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Build and push hello-service to GitHub Container Registry
        uses: docker/build-push-action@v2.10.0
        with:
          context: hello-service
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/hello-service:${{ env.TAG }}
            ghcr.io/${{ github.repository }}/hello-service:latest
      - name: Build and push hello-service to Azure Container Registry
        uses: Azure/acr-build@v1
        with:
          service_principal: ${{ secrets.CLIENT_ID }}
          service_principal_password: ${{ secrets.CLIENT_SECRET }}
          tenant: ${{ secrets.TENANT_ID }}
          registry: containercentral
          repository: hello-service
          folder: ./
          dockerfile: ./hello-service/Dockerfile
          tag: ${{ env.TAG }}
      - name: Build and push world-service to GitHub Container Registry
        uses: docker/build-push-action@v2.10.0
        with:
          context: world-service
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/world-service:${{ env.TAG }}
            ghcr.io/${{ github.repository }}/world-service:latest
      - name: Build and push greeting-service to GitHub Container Registry
        uses: docker/build-push-action@v2.10.0
        with:
          context: greeting-service
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/greeting-service:${{ env.TAG }}
            ghcr.io/${{ github.repository }}/greeting-service:latest
