name: Trigger auto deployment for greeting-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'greeting-service/**'
    - '.github/workflows/greeting-service-AutoDeployTrigger-1c360e4e-d37d-4970-9492-cfe40a0f80b5.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containercentral.azurecr.io
          username: ${{ secrets.GREETINGSERVICE_REGISTRY_USERNAME }}
          password: ${{ secrets.GREETINGSERVICE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containercentral.azurecr.io/dapr-demos/greeting-service:${{ github.sha }}
          file: ./greeting-service/Dockerfile
          context: ./greeting-service/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GREETINGSERVICE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n greeting-service -g rg-dynamicamoeba --server containercentral.azurecr.io --username  ${{ secrets.GREETINGSERVICE_REGISTRY_USERNAME }} --password ${{ secrets.GREETINGSERVICE_REGISTRY_PASSWORD }}
            az containerapp update -n greeting-service -g rg-dynamicamoeba --image containercentral.azurecr.io/dapr-demos/greeting-service:${{ github.sha }}
