name: Trigger auto deployment for world-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'world-service/**'
    - '.github/workflows/world-service-AutoDeployTrigger-9f7a241a-8c22-4413-957b-52114b0c661e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containercentral.azurecr.io
          username: ${{ secrets.WORLDSERVICE_REGISTRY_USERNAME }}
          password: ${{ secrets.WORLDSERVICE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containercentral.azurecr.io/dapr-demos/world-service:${{ github.sha }}
          file: ./world-service/Dockerfile
          context: ./world-service/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WORLDSERVICE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n world-service -g rg-dynamicamoeba --server containercentral.azurecr.io --username  ${{ secrets.WORLDSERVICE_REGISTRY_USERNAME }} --password ${{ secrets.WORLDSERVICE_REGISTRY_PASSWORD }}
            az containerapp update -n world-service -g rg-dynamicamoeba --image containercentral.azurecr.io/dapr-demos/world-service:${{ github.sha }}
